"""Freeze the bundled variable font for jsPDF (which reads its default outlines).

Run with Python + fonttools. Generated JS also supports offline file:// use.
The source font defaults to weight 100; browser CSS can vary it, jsPDF cannot.
"""
import base64
import json
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "dist/solbook_question_maker_portable/app/assets/fonts"
SOURCE = FONT_DIR / "NotoSansKR-VF.ttf"


def main():
    fonts = {}
    for style, weight, label in [("normal", 400, "Regular"), ("bold", 800, "ExtraBold")]:
        font = instantiateVariableFont(TTFont(SOURCE), {"wght": weight}, inplace=True)
        font["OS/2"].usWeightClass = weight
        font["OS/2"].fsSelection = (font["OS/2"].fsSelection & ~0x60) | (0x20 if weight >= 700 else 0x40)
        font["head"].macStyle = (font["head"].macStyle & ~1) | (1 if weight >= 700 else 0)
        names = {1: "PDF Lab Solbook Print", 2: label, 3: f"PDFLabSolbookPrint-{label}",
                 4: f"PDF Lab Solbook Print {label}", 6: f"PDFLabSolbookPrint-{label}",
                 16: "PDF Lab Solbook Print", 17: label}
        for name in font["name"].names:
            if name.nameID in names:
                font["name"].setName(names[name.nameID], name.nameID, name.platformID, name.platEncID, name.langID)
        output = FONT_DIR / f"NotoSansKR-Print-{label}.ttf"
        font.save(output)
        fonts[style] = base64.b64encode(output.read_bytes()).decode("ascii")
        print(f"{output.name}: weight={weight}, bytes={output.stat().st_size}")
    bundle = FONT_DIR / "NotoSansKR-Print.base64.js"
    bundle.write_text("// Generated by tools/build_solbook_pdf_fonts.py; weights 400 / 800.\n"
                      + "window.PDFLAB_PRINT_PDF_FONTS_BASE64=" + json.dumps(fonts) + ";\n", encoding="utf-8")


if __name__ == "__main__":
    main()
